/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.util.ArrayList;

/**
 *
 * @author Dilan Sachintha
 */
public class RegisteredCustomerPay extends javax.swing.JFrame {
    

    /**
     * Creates new form RegisteredCustomerPay
     */
    public RegisteredCustomerPay(ArrayList<String> selected_seats, String schedule_id) {
        initComponents();
        setLabels(selected_seats, schedule_id);
    }

    public void setLabels(ArrayList<String> selected_seats, String schedule_id){
        
        String sql = "select * from (select * from seat where seat_id=\"14\")"
                + " as A natural left join class natural left join"
                + " (select * from price where route_id=(select route_id "
                + "from flight_schedule where"
                + " flight_schedule_id=\"2\")) as B;";
        
        String insert = "";
        
        for(int i = 0; i < selected_seats.size() ; i++){
            insert = insert + "seat_id='"+selected_seats.get(i)+"' or ";
        }
        
        System.out.println(insert.substring(0, insert.length()-5));
        
        int econ_seats;
        int busi_seats;
        int plati_seats;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_econ_seat = new javax.swing.JLabel();
        lbl_busi_seat = new javax.swing.JLabel();
        lbl_plati_seat = new javax.swing.JLabel();
        lbl_econ_price = new javax.swing.JLabel();
        lbl_busi_price = new javax.swing.JLabel();
        lbl_plati_price = new javax.swing.JLabel();
        lbl_seat_total = new javax.swing.JLabel();
        lbl_price_total = new javax.swing.JLabel();
        btn_book = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Confirm Payment");

        jLabel2.setText("Economy Seats : ");

        jLabel3.setText("Business Seats : ");

        jLabel4.setText("Platinum Seats : ");

        lbl_econ_seat.setText("jLabel5");

        lbl_busi_seat.setText("jLabel6");

        lbl_plati_seat.setText("jLabel7");

        lbl_econ_price.setText("jLabel8");

        lbl_busi_price.setText("jLabel9");

        lbl_plati_price.setText("jLabel10");

        lbl_seat_total.setText("jLabel11");

        lbl_price_total.setText("jLabel12");

        btn_book.setText("Confirm Payment");
        btn_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_busi_seat)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_busi_price))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_econ_seat)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_econ_price))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_book)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_seat_total)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_plati_seat)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_plati_price)
                                        .addComponent(lbl_price_total))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_econ_seat)
                    .addComponent(lbl_econ_price))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_busi_seat)
                    .addComponent(lbl_busi_price))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_plati_seat)
                    .addComponent(lbl_plati_price))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_seat_total)
                    .addComponent(lbl_price_total))
                .addGap(43, 43, 43)
                .addComponent(btn_book)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_book;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_busi_price;
    private javax.swing.JLabel lbl_busi_seat;
    private javax.swing.JLabel lbl_econ_price;
    private javax.swing.JLabel lbl_econ_seat;
    private javax.swing.JLabel lbl_plati_price;
    private javax.swing.JLabel lbl_plati_seat;
    private javax.swing.JLabel lbl_price_total;
    private javax.swing.JLabel lbl_seat_total;
    // End of variables declaration//GEN-END:variables
}
