/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JCheckBox;

/**
 *
 * @author Dilan Sachintha
 */
public class UserBooking extends javax.swing.JFrame {
    
    private ArrayList<String> selected_seats;

    /**
     * Creates new form UserBooking
     */
    public UserBooking(String schedule_id, String selected_class) {
        initComponents();
        selected_seats = new ArrayList<>();
        getSeats(schedule_id, selected_class);
    }
    
    public void getSeats(String schedule_id, String selected_class){
        String sql = "select * from (select * from (select * from (select * from flight_schedule"
                + " where flight_schedule_id='"+schedule_id+"') as A natural left join aircraft "
                + "natural left join seat) as B natural left join class where "
                + "class_id=(select class_id from class where class='"+selected_class+"')) "
                + "as D left join booking using(flight_schedule_id,seat_id) "
                + "where booking_id is null;";
        
        try{
            ResultSet rs = Database.getData(sql);
            int bounds = 0;
            
            while(rs.next()){                
                JCheckBox checkBox_seat = new javax.swing.JCheckBox();
                checkBox_seat.setText("Seat No " + rs.getString("seat_no"));
                checkBox_seat.setName(rs.getString("seat_id"));
                checkBox_seat.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        System.out.println(checkBox_seat.getName());
                        selected_seats.add(checkBox_seat.getName());
                    }
                });
                checkBox_seat.setBounds(140,95+bounds,100,30);
                this.add(checkBox_seat);
                bounds+=35;
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_book = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Remaining Seats : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Confirm Booking");

        btn_book.setText("Book");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160)
                        .addComponent(btn_book)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_book))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_book;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
