/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dilan Sachintha
 */
public class UserHome extends javax.swing.JFrame {
    
    private String[] airports;
    public static String airport_from;
    public static String airport_to;

    /**
     * Creates new form UserHome
     */
    public UserHome() {
        
        setComboBoxData();
        
        initComponents();
        
        cmbbx_from.setModel(new javax.swing.DefaultComboBoxModel<>(airports));
        cmbbx_to.setModel(new javax.swing.DefaultComboBoxModel<>(airports));
        airport_from = cmbbx_from.getItemAt(0);
        airport_to = cmbbx_to.getItemAt(0);
    }
    
    public void setComboBoxData(){
        String sql = "select airport_name from airport";
        ResultSet rs = Database.getData(sql);
        
        try {
            //Connec
            
            rs.last();
        
            airports = new String[rs.getRow()];
            rs.beforeFirst();
            
            int i=0;
            while(rs.next()){
                airports[i] = rs.getString("airport_name");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_view_flights = new javax.swing.JButton();
        cmbbx_from = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbbx_to = new javax.swing.JComboBox<>();
        btn_previous_bookings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_view_flights.setText("View Flights");
        btn_view_flights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_flightsActionPerformed(evt);
            }
        });

        cmbbx_from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbx_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbx_fromActionPerformed(evt);
            }
        });

        jLabel1.setText("To");

        cmbbx_to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbx_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbx_toActionPerformed(evt);
            }
        });

        btn_previous_bookings.setText("View My Bookings");
        btn_previous_bookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previous_bookingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbbx_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbbx_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_view_flights)
                        .addGap(139, 139, 139)
                        .addComponent(btn_previous_bookings)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbx_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cmbbx_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_view_flights)
                    .addComponent(btn_previous_bookings))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_view_flightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_flightsActionPerformed
        UserFlightDisplay ufd = new UserFlightDisplay();
        this.setVisible(false);
        ufd.setVisible(true);
    }//GEN-LAST:event_btn_view_flightsActionPerformed

    private void cmbbx_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbx_fromActionPerformed
        airport_from = cmbbx_from.getSelectedItem().toString();
    }//GEN-LAST:event_cmbbx_fromActionPerformed

    private void cmbbx_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbx_toActionPerformed
        airport_to = cmbbx_to.getSelectedItem().toString();
    }//GEN-LAST:event_cmbbx_toActionPerformed

    private void btn_previous_bookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previous_bookingsActionPerformed
        PreviousBooking pb = new PreviousBooking();
        this.setVisible(false);
        pb.setVisible(true);
    }//GEN-LAST:event_btn_previous_bookingsActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_previous_bookings;
    private javax.swing.JButton btn_view_flights;
    private javax.swing.JComboBox<String> cmbbx_from;
    private javax.swing.JComboBox<String> cmbbx_to;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
